repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files

-   repo: local
    hooks:
    -   id: pytest-check
        name: PyTest Runner
        entry: pytest
        language: system
        pass_filenames: false
        always_run: true
    # -   id: sort-imports
    #     name: Sort Imports
    #     entry: isort .
    #     language: system
    #     types: [python]
    #     args: ["--profile", "black", "--filter-files"]
    #     pass_filenames: false
    #     always_run: true
